name: Go Deploy

on:
  workflow_dispatch:
    inputs:
      kurohelperservice_ref:
        description: 'kurohelper-service 依賴使用的版本 ref'
        required: false
        type: string
        default: 'main'

permissions:
  contents: read
  actions: read

jobs:
  go-deploy:
    permissions:
      contents: read
      actions: write
    uses: kuro-helper/.github/.github/workflows/go-deploy.yml@main
    with:
      kurohelperservice_ref: ${{ inputs.kurohelperservice_ref }}
    secrets: inherit